version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      major-updates:
        update-types:
          - "major"
        patterns:
          - "*"
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
