/**
 * @file FormulaHelp — a small "?" trigger ({@link FormulaHelpButton}) that
 * opens a read-only modal documenting the formula mini-language accepted
 * by {@link formulaParser}: the list of substitutable variables, the
 * arithmetic helper functions (floor/ceil/min/max), and a few real
 * formulas from this project's own spell/item data as worked examples.
 *
 * Placed next to a formula {@link FormField} via its `labelExtra` slot, so
 * it's visible to exactly whoever can already edit that field (spell/item/
 * action create-and-edit forms) — this component adds no permission logic
 * of its own.
 *
 * The variable list is never hand-typed here: it's generated by
 * {@link listFormulaVariables}, which reflects over the same table
 * `substituteVariables` uses internally to perform substitution. A
 * variable added to (or removed from) that table changes what appears
 * here automatically. See the "FormulaHelp / do not hardcode the variable
 * list" note in CLAUDE.md and the @file header of `formulaParser.ts` for
 * why this matters: FLAW was once documented in prose without ever being
 * wired up, and nothing caught it for months.
 */

import { useState } from "react";
import { listFormulaVariables } from "../../../utils/formulaParser";
import { BASE_SPELLS } from "../../../data/spells";
import { BASIC_EQUIPMENTS } from "../../../data/equipment";
import { ModalShell } from "./ModalShell";

/**
 * Looks up a real spell's formula by name in {@link BASE_SPELLS}, so the
 * help panel's worked examples are always an actual formula from this
 * project's data rather than a copy that can silently go stale.
 *
 * @remarks Falls back to an empty string (with a dev console warning)
 * instead of throwing if the name isn't found — a rename in `spells.ts`
 * should degrade this documentation panel gracefully, not crash every
 * spell/item/action form in the app.
 */
function realSpellFormula(name: string): string {
  const spell = BASE_SPELLS.find((s) => s.name === name);
  if (!spell) {
    console.warn(`FormulaHelp: spell "${name}" not found in BASE_SPELLS.`);
    return "";
  }
  return spell.formula || spell.damage;
}

/** Same as {@link realSpellFormula}, looking up an item in {@link BASIC_EQUIPMENTS} instead. */
function realItemFormula(name: string): string {
  const item = BASIC_EQUIPMENTS.find((i) => i.name === name);
  if (!item?.formula) {
    console.warn(`FormulaHelp: item "${name}" not found in BASIC_EQUIPMENTS.`);
    return "";
  }
  return item.formula;
}

/**
 * The arithmetic helper functions the parser accepts, for the "Math
 * helpers" section. A short, hand-written list rather than a generated
 * one: unlike the variable table, these are fixed parts of the formula
 * *grammar* (see the `Parser` class in `formulaParser.ts`), not values
 * pulled from character data, so there's no equivalent risk of a function
 * being "documented" without actually being wired up.
 */
const FUNCTIONS: { signature: string; desc: string }[] = [
  { signature: "floor(x)", desc: "Rounds down" },
  { signature: "ceil(x)", desc: "Rounds up" },
  { signature: "min(a, b)", desc: "Smaller of the two" },
  { signature: "max(a, b)", desc: "Larger of the two" },
];

/**
 * Worked examples pulled from real spell data, chosen to cover the
 * notations a GM is most likely to get wrong: a variable glued directly
 * to a die, an implicit dice count, and the two dynamic-dice helpers
 * (dice count growing with level, and dice size growing with level).
 */
const EXAMPLES: { formula: string; note: string }[] = [
  {
    formula: realSpellFormula("Immolating Breath (Dragonform)"),
    note: "KEY glued directly to a die: one d20 per point of your key stat, not \"KEY times d20\".",
  },
  {
    formula: realSpellFormula("Glacier Strike"),
    note: "Implicit dice count: \"d66\" is a single roll on the book's d66 table, equivalent to 1d66, not 6d6.",
  },
  {
    formula: realSpellFormula("Shadow Blast"),
    note: "Dynamic dice count: incrementdice(1, level) adds one extra d12 every 5 levels, on top of a flat KEY bonus.",
  },
  {
    formula: realSpellFormula("Entice"),
    note: "Dynamic dice size: 1dstepdice(level, 4, 8, 10, 12) rolls a bigger single die at level 5, 10, and 15, not more dice.",
  },
];

/**
 * Renders a small, accessible "?" button that opens {@link FormulaHelpModal}
 * on click. Self-contained: manages its own open/closed state, so a call
 * site only needs to render `<FormulaHelpButton />` next to a formula field.
 */
export function FormulaHelpButton() {
  const [open, setOpen] = useState(false);

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Formula syntax help"
        className="flex items-center justify-center w-3.5 h-3.5 shrink-0 rounded-full border border-stone-600 text-stone-500 text-[9px] leading-none hover:border-amber-600 hover:text-amber-400 outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-1 focus-visible:ring-offset-stone-900 transition-colors"
      >
        ?
      </button>
      {open && <FormulaHelpModal onClose={() => setOpen(false)} />}
    </>
  );
}

/**
 * Read-only modal: the list of every formula variable the parser accepts
 * (generated, see {@link listFormulaVariables}), followed by a few real
 * formulas as worked examples. No editing, no permission checks.
 */
function FormulaHelpModal({ onClose }: { onClose: () => void }) {
  const variables = listFormulaVariables();

  return (
    <ModalShell
      title="Formula syntax help"
      accent="amber"
      onClose={onClose}
      maxWidth="max-w-sm"
      footer={
        <button
          onClick={onClose}
          className="w-full py-2 rounded-lg border border-stone-700 text-stone-400 text-sm hover:bg-stone-800 transition-colors"
        >
          Close
        </button>
      }
    >
      <div className="p-4 flex flex-col gap-4">
        <section>
          <h4 className="text-[10px] uppercase tracking-wide text-stone-500 mb-1.5">
            Available variables
          </h4>
          <div className="flex flex-wrap gap-1.5">
            {variables.map((v) => (
              <span
                key={v.name}
                className="font-mono text-[10px] px-1.5 py-0.5 rounded border border-stone-700 bg-stone-800/60 text-amber-300/90 break-all"
              >
                {[v.name, ...v.aliases].join(" / ")}
              </span>
            ))}
          </div>
        </section>

        <section>
          <h4 className="text-[10px] uppercase tracking-wide text-stone-500 mb-1.5">
            Math helpers
          </h4>
          <div className="flex flex-col gap-1">
            {FUNCTIONS.map((fn) => (
              <div key={fn.signature} className="flex items-baseline gap-2">
                <code className="font-mono text-[10px] text-amber-300/90 shrink-0">
                  {fn.signature}
                </code>
                <span className="text-[10px] text-stone-500">{fn.desc}</span>
              </div>
            ))}
          </div>
          <p className="text-[10px] text-stone-500 mt-1.5 leading-snug">
            Math.floor(), Math.ceil(), Math.min(), Math.max() also work, same
            meaning, e.g. Rusty Mail's armor formula "
            <code className="font-mono text-amber-300/90">
              {realItemFormula("Rusty Mail")}
            </code>
            ".
          </p>
        </section>

        <section>
          <h4 className="text-[10px] uppercase tracking-wide text-stone-500 mb-1.5">
            Examples from real spells
          </h4>
          <div className="flex flex-col gap-2">
            {EXAMPLES.map((ex) => (
              <div
                key={ex.note}
                className="rounded border border-stone-700 bg-stone-900/60 px-2 py-1.5"
              >
                <code className="block font-mono text-[11px] text-amber-300 break-all">
                  {ex.formula}
                </code>
                <p className="text-[10px] text-stone-500 mt-1 leading-snug">
                  {ex.note}
                </p>
              </div>
            ))}
          </div>
        </section>
      </div>
    </ModalShell>
  );
}
